[package]
name = "rustmas"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "solve"
path = "src/bin/solve/main.rs"

[[bin]]
name = "fetch"
path = "src/bin/fetch/main.rs"

[lib]
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.5", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = { version = "0.13.4", features = ["blocking", "form"] }
thiserror = "2.0.19"
