[package]
name = "rustmas"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "run"
path = "src/bin/run.rs"

[[bin]]
name = "init"
path = "src/bin/init/main.rs"

[lib]
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
dotenvy = "0.15.7"
reqwest = { version = "0.13.4", features = ["blocking"] }
thiserror = "2.0.19"
